# Generated by Django 2.2.2 on 2019-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190704_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('created', 'Created'), ('refunded', 'Refunded'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
