# Generated by Django 2.2.2 on 2019-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190704_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('created', 'Created'), ('refunded', 'Refunded'), ('shipped', 'Shipped')], default='created', max_length=120),
        ),
    ]
